version: '3.8'
services:  
  api:    
    build: ./api    
    container_name: api_backend    
    ports:      
      - '3000:3000'    
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules